import Header from "./Header"

export const metadata = {
  title: 'Ecommerce App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
    viewport: {
      width: 'device-width',
      initialScale: 1,
      maximumScale: 1,
    },
  },
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <head>
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" precedence="default" />
  </head>
      <body>
        <Header/>
        {children}
      </body>
    </html>
  )
}
